# VAE model configuration (Generic)
# Configurable VAE with selectable encoder/decoder architectures

name: "vae"
encoder_name: "locatello"
decoder_name: "locatello"
latent_dim: 10
decoder_output_dist: "bernoulli"
use_batchnorm: false

# Optional: Override encoder/decoder dimensions (if None, uses latent_dim)
# encoder_output_dim: null
# decoder_input_dim: null
