# VAE model configuration (Locatello SBD)
# Locatello architecture with Spatial Broadcast Decoder

name: "vae_locatello_sbd"
encoder_name: "locatello"
decoder_name: "sbd"
latent_dim: 10
decoder_output_dist: "bernoulli"
use_batchnorm: false

# Optional: Override encoder/decoder dimensions (if None, uses latent_dim)
# encoder_output_dim: null
# decoder_input_dim: null
