# VAE model configuration (Montero Small)
# Small CNN architecture for 64x64 images

name: "vae_montero_small"
encoder_name: "montero_small"
decoder_name: "montero_small"
latent_dim: 10
decoder_output_dist: "bernoulli"
use_batchnorm: false

# Optional: Override encoder/decoder dimensions (if None, uses latent_dim)
# encoder_output_dim: null
# decoder_input_dim: null
