# VAE model configuration (Chen MLP)
# MLP-based VAE architecture for flat image inputs

name: "vae_chen_mlp"
encoder_name: "chen_mlp"
decoder_name: "chen_mlp"
latent_dim: 10
decoder_output_dist: "bernoulli"
use_batchnorm: false

# Optional: Override encoder/decoder dimensions (if None, uses latent_dim)
# encoder_output_dim: null
# decoder_input_dim: null
