# Dataset configuration for CelebA
# Configured for training on the CelebA dataset

name: "celeba"
root: "data/celeba/"
subset: 1.0
resize_algorithm: "LANCZOS"
crop_faces: True
crop_margins: [0.8, 0.8, 2.2, 0.9]
force_download: false
load_into_memory: true