# Dataset configuration for DSprites
# Uses the default DSprites configuration from the schema

name: "dsprites" 
root: "data/dsprites/"
selected_factors: ['color', 'shape', 'scale', 'posX', 'posY']
not_selected_factors_index_value: {'orientation': 0}
drop_color_factor: true
subset: 1.0
