# Dataset configuration for Shapes3D
# Configured for training on the 3D Shapes dataset

name: "shapes3d"
root: "data/shapes3d/" 
selected_factors: "all"
not_selected_factors_index_value: null
subset: 1.0
