# GroupTheory loss config with Beta VAE base
# Inherits from base.yaml and overrides specific loss configuration

defaults:
  - base
  - _self_

trainer:
  loss:
    base_loss_name: "betavae"
    base_loss_kwargs:
      beta: 16 
      rec_dist: "gaussian"
      log_kl_components: true
