# @package _global_
# DSprites dataset configuration - merges into global config

# Dataset-specific overrides
trainer:
  dataset:
    name: "dsprites"
    root: "data/dsprites/"
    selected_factors: "all"
    not_selected_factors_index_value: null
    subset: 1.0
    transforms: null
