# @package _global_
# Shapes3D dataset configuration - merges into global config

# Dataset-specific overrides
trainer:
  dataset:
    name: "shapes3d"
    root: "data/shapes3d/"
    selected_factors: "all"
    not_selected_factors_index_value: null
    subset: 1.0
    transforms: null
