# GroupTheory loss config with Annealed VAE base
# Inherits from base.yaml and overrides specific loss configuration

defaults:
  - base
  - _self_

trainer:
  loss:
    name: "group_theory"
    # Base loss configuration
    rec_dist: "gaussian"
    device: "cuda"
    commutative_weight: 1
    commutative_component_order: 2
    commutative_comparison_dist: "gaussian"
    meaningful_weight: 1.0
    meaningful_component_order: 1
    meaningful_transformation_order: 1
    meaningful_critic_gradient_penalty_weight: 10.0
    meaningful_critic_lr: 1e-4
    meaningful_n_critic: 1
    deterministic_rep: true
    group_action_latent_range: 2.0
    group_action_latent_distribution: "uniform"
    comp_latent_select_threshold: 0.1
    base_loss_state_dict: null
    warm_up_steps: 0
    schedulers_kwargs:
      - name: linear
        kwargs:
          param_name: meaningful_weight
          initial_value: 0.0  # Start with no meaningful loss
          final_value: 10     # End with full meaningful loss
          total_steps: 300000
