
loss_type: "wgan_gp"
loss_kwargs:
  gradient_penalty_weight: 10.0
d_arch: "locatello"
d_kwargs:
  spectral_norm: false
d_optimizer_type: "adam"
d_optimizer_kwargs:
  lr: 0.0001
  betas: [0.9, 0.999]
