# AnnealedVAE configuration for Shapes3D dataset
# This configuration follows the ExperimentConfig schema and produces the desired output

hydra:
  run:
    dir: .
  output_subdir: null

defaults:
  - base
  - _self_

# Override specific settings for AnnealedVAE
trainer:
  loss:
    name: "annealedvae"
    gamma: 100.0
    C_init: 0.0
    C_fin: 25.0
    anneal_steps: 100000
    rec_dist: "gaussian"
    log_kl_components: true
    
  dataset:
    name: "shapes3d"
    root: "data/shapes3d/"
    selected_factors: "all"
    not_selected_factors_index_value: null
    subset: 1.0
    transforms: null
