# S-VAE Toroidal model configuration
# Toroidal VAE for learning periodic latent factors

name: "toroidal_vae"
encoder_name: "locatello"
decoder_name: "locatello"
latent_dim: 10
decoder_output_dist: "bernoulli"
use_batchnorm: false
device: "auto"
img_size: null
# Toroidal-specific parameters
n_angle_dim: 2  # Number of periodic dimensions
