# Training Beta-TC-VAE on Shapes3D dataset
# Configuration for Total Correlation disentanglement

defaults:
  - base_config
  - dataset: shapes3d
  - model: vae_burgess
  - loss: betatcvae
  - _self_

step_unit: "epoch"
max_steps: 80

# Reproducibility
determinism:
  seed: 456
  use_cuda_det: true
  enforce_det: false

# Model configuration
model:
  device: "auto"
  latent_dim: 15

# Loss configuration
loss:
  beta: 6.0
  alpha: 1.0
  gamma: 1.0
  rec_dist: "bernoulli"
  log_kl_components: true

# Optimizer
optimizer:
  name: "Adam"
  lr: 5e-4
  weight_decay: 0.0

# Learning rate scheduling
lr_scheduler:
  name: "CosineAnnealingLR"
  T_max: 80
  eta_min: 1e-6
  verbose: false

# Data loading
dataloader:
  batch_size: 64
  num_workers: 4
  shuffle: true
  pin_memory: true

# Logging
logging:
  enabled: true
  loss_interval_type: "iter"
  loss_iter_interval: 100
  metrics_interval_type: "iter"
  metrics_iter_interval: 500

# Checkpointing
checkpoint:
  enabled: true
  every_n_steps: 15
  step_type: "epoch"
  save_dir: "checkpoints/betatcvae_shapes3d"
  save_viz: true

# Performance optimization
torch_compile:
  enabled: true
  mode: "reduce-overhead"
  backend: "inductor"
