# @package _global_

defaults:
  - base_config
  - override dataset: shapes3d
  - override model: vae_locatello
  - override loss: betavae
  - _self_

experiment:
  experiment_id: train_betavae_shapes3d_example
  results_dir: "results/"
  seeds: [1, 2, 3]
  resume: False

trainer:
  max_steps: 10000
  step_unit: "iter"
  
  dataset:
    subset: 1 # Use a subset for faster training in this example

  model:
    latent_dim: 10
    
  loss:
    beta: 10
    
  dataloader:
    batch_size: 64
    num_workers: 4

  checkpoint:
    enabled: True
    return_chkpt: True
    every_n_steps: 5000
    step_type: "iter"
    save_master_dir: null # Will be set by experiment manager
