# GroupTheory loss config with FactorVAE base
# Inherits from base.yaml and overrides specific loss configuration

defaults:
  - /models/g-vae/g-meaningful/g-meaningful_base
  - _self_

trainer:
  loss:
    base_loss_name: "factorvae"
    base_loss_kwargs:
      gamma: 10.0           # Weight of the TC loss term
      discr_lr: 0.0001      # Discriminator learning rate
      discr_betas: [0.5, 0.9] # Discriminator Adam betas
      rec_dist: "gaussian"
      log_kl_components: true
